### ISSUE TITLE
🚀 Project: MVVm Architectured TODO List

### ISSUE THREAD

**Issue by Pranishkafle6175** [Prodigy-InfoTech/Android-Development-Projects#2]
### 🔖 Project description

The TO-DO list app isefficiently designed and structured using MVVM
architecture, ensuring a clear separation of Ui and the business logic. It
Efficiently manages tasks with features like saving, updating, and deleting. The app shows the high quality architectured code and Good UI

### 🎤 Pitch

For the beginner They don't care about the quality of code and just make a functioning app . This is not a good approach ,My app is basically for beginner who want to write good quality architectured code. Users can see the code Written in MVVM architecture and properly managed. This can be a great learning tool for beginner. Also users can use My app TODO list to easily manage tgheir daily lifestyle, I have priority based List so it would be very easy to manage all.

### 👀 Have you spent some time to check if this issue has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/Prodigy-InfoTech/.github/blob/main/CODE_OF_CONDUCT.md)

**Comment by Pranishkafle6175** [comment]
Hello ,
You asked me to send code as a folder i have clone your repo inside that
repo i created a folder and then pushed where do i have to create folder ?
I am little confused!

**Comment by prodigyinfotech** [comment]
It was not added correctly as it was also not linking back to other repo.
Please check guidelines for using submodule functionality which you were trying to perform. Alternatively, copy your project folder into repo and submit it.

**Comment by Pranishkafle6175** [comment]
I did the same sir i copied the folder and pasted inside the repo i didnt
knew what went incorrect!!

**Comment by prodigyinfotech** [comment]
Hey @Pranishkafle6175 please refer some guides on how to properly commit and add files
